# Generated by Django 3.0.4 on 2020-03-31 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=60)),
                ('genre', models.CharField(choices=[('Classic', 'Classic'), ('Fiction', 'Fiction'), ('Romance', 'Romance'), ('History', 'History'), ('Drama', 'Drama'), ('Politics', 'Politics'), ('Thriler', 'Thriler'), ('Poetry', 'Poetry')], max_length=20)),
                ('cover', models.FileField(blank=True, null=True, upload_to='')),
                ('description', models.TextField()),
                ('language', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=30)),
                ('dislikedBooks', models.ManyToManyField(blank=True, default=None, null=True, related_name='dislikedBy', to='blog.Book')),
                ('likedBooks', models.ManyToManyField(blank=True, default=None, null=True, related_name='likedBy', to='blog.Book')),
                ('recommendedBooks', models.ManyToManyField(blank=True, default=None, null=True, related_name='recommendedTo', to='blog.Book')),
                ('similarUsers', models.ManyToManyField(blank=True, default=None, null=True, related_name='similarTo', to='blog.Profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=60)),
                ('value', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='blog.Profile')),
            ],
        ),
    ]
