# Generated by Django 3.0.4 on 2020-04-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200404_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('Classic', 'Classic'), ('Fiction', 'Fiction'), ('Romance', 'Romance'), ('History', 'History'), ('Drama', 'Drama'), ('Politics', 'Politics'), ('Thriler', 'Thriler'), ('Poetry', 'Poetry')], max_length=15)
        ),
    ]
