# Generated by Django 3.0.4 on 2020-04-15 16:49

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200415_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre1',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Classic', 'Classic'), ('Fiction', 'Fiction'), ('Romance', 'Romance'), ('History', 'History'), ('Drama', 'Drama'), ('Politics', 'Politics'), ('Thriler', 'Thriler'), ('Poetry', 'Poetry')], default=0, max_length=16),
            preserve_default=False,
        ),
    ]
