# Generated by Django 3.0.4 on 2020-04-15 16:58

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_book_genre1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='genre1',
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Classic', 'Classic'), ('Fiction', 'Fiction'), ('Romance', 'Romance'), ('History', 'History'), ('Drama', 'Drama'), ('Politics', 'Politics'), ('Thriler', 'Thriler'), ('Poetry', 'Poetry')], max_length=60),
        ),
    ]
